### ISSUE TITLE
Test suite on Debian/Ubuntu

### ISSUE THREAD

**Issue by gunnarhj** [mike-fabian/ibus-typing-booster#157] opened 2021-02-23 12:37 UTC
Hi!

I have enabled the test suite when building ibus-typing-booster on Debian and Ubuntu. Had to skip some tests to make it build, though.

There are mismatches in tests involving the en_US and sv_SE dictionaries, and I suspect they are caused by different dict versions in Debian compared to Fedora.

                       Fedora        Debian
                       version       version

    hunspell-en-us     20140811      20191006
    hunspell-sv        2.28          2.40

Another problem is `test_hi_inscript2` and `test_mr_inscript2` which triggered "ValueError: minput_open_im() failed".

I also noticed that `python3-hunspell` is redundant as build depend if `python3-enchant` is present. Currently the latter is a build depend.

Please find the [build dependencies](https://salsa.debian.org/input-method-team/ibus-typing-booster/-/blob/master/debian/control) and the [patch](https://salsa.debian.org/input-method-team/ibus-typing-booster/-/blob/master/debian/patches/skip-some-tests.patch) I used to prevent test failures. A build log without those steps to prevent test failures can be found here:

https://launchpadlibrarian.net/524649277/buildlog_ubuntu-hirsute-amd64.ibus-typing-booster_2.10.5-1~testfailures_BUILDING.txt.gz

Maybe these things are not so much to do about. Different versions of spellcheck dicts will probably happen from time to time. Possibly the changes I made via the patch to skip `test_hi_inscript2` and `test_mr_inscript2` are suitable for upstream. Or are you aware of a way to fix that `minput_open_im()` problem?

**Comment by mike-fabian** [comment] 2021-03-01 18:05
Oh, my commit closed this although the commit did address only one problem.

**Comment by mike-fabian** [comment] 2021-03-01 18:23
> Possibly the changes I made via the patch to skip `test_hi_inscript2` and `test_mr_inscript2` are suitable for upstream. 

Yes, thank you, I just committed these to the master branch.

> Or are you aware of a way to fix that `minput_open_im()` problem?

It is not really a problem, only the input methods hi-inscript2 and mr-inscript2
don't exist on some distributions.

`minput_open_im()` fails because these are not available on Debian.

These inscript2 input methods were developed by my colleague Parag Nemade
and they are not yet upstream in m17n-db. Originally these were considered
not yet finished and therefore not submitted upstream. But now they have been
stable with no changes for many years and should certainly be included upstream.

Unfortunately the m17n project is not very responsive now so we don't know when
we will get this in upstream.

For the SuSE package I build, I include these as an extra tar ball:


See this

https://build.opensuse.org/package/show/home:mike-fabian/ibus-typing-booster

There is the tar ball with the inscript2 input methods:

inscript2-20160423.tar.gz

And a patch I made in 2019 which fixes a few syntax errors in the input methods for the mni and sat languages: 

m17n-db-1.8.0-inscript2-mni-sat.patch

No changes since then.

So on SuSE, the ibus-typing-booster package adds these input methods to m17n-db.

On Fedora, they are added in the m17n-db package, see:

https://src.fedoraproject.org/rpms/m17n-db/tree/rawhide

This is better, that’s where they belong. But I don’t maintain the m17n-db package on SuSE so adding them to ibus-typing-booster was easier.

They should go upstream to the m17n-db project, I’ll try again to get them upstream.

They are completely optional, of course ibus-typing-booster works fine without them,
you just cannot use these specific input methods then.

So I think you patch is perfect to skip the test.

Tests for input methods which don't exist should be skipped, one cannot assume that the list of available input methods in m17n-db is the same everywhere.

**Comment by mike-fabian** [comment] 2021-03-01 18:39
> I also noticed that `python3-hunspell` is redundant as build depend if `python3-enchant` is present. Currently the latter is a build depend.

Yes, ibus-typing-booster supports both `python3-hunspell` and `python3-enchant` but ignores `python3-hunspell` and uses only `python3-enchant` if both are available.

There are some distributions where python3-enchant is not available but python3-hunspell
is available. For example, this seems to be the case on FreeBSD. Therefore,
I tried to make ibus-typing-booster work with both and fall back to python3-hunspell
if python3-enchant is not available.

I very rarely test with python3-hunspell though, sometimes I remove
the python3-enchant package from my system and run the test suite and
do some manual tests to see whether the python3-hunspell support still
works, but not very often, only when I made some changes where I
really suspect it might affect the python3-hunspell support.

I hope the FreeBSD package maintainer will scream if it stops working without me noticing.

So I think not using python3-hunspell in your build dependencies is fine.
I also use only python3-enchant in the build requirements on Fedora and openSUSE.

**Comment by mike-fabian** [comment] 2021-03-01 19:03
> There are mismatches in tests involving the en_US and sv_SE dictionaries, and I suspect they are caused by different dict versions in Debian compared to Fedora.
> 
> ```
>                    Fedora        Debian
>                    version       version
> 
> hunspell-en-us     20140811      20191006
> hunspell-sv        2.28          2.40
> ```

I am not sure what to do about failing tests because of different dictionary versions.

The Debian versions seem newer than the Fedora versions and I also think that is the cause for the test failure.

I don’t know how I could easily find the versions of the dictionaries.
The version seems to be in the package names, but not in the dictionary files.

The dictionaries are loaded with this function:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/engine/itb_util.py#L2956

`get_hunspell_dictionary_wordlist()` just searches for the .dic and .aff files in a few standard locations and then tries to load files in the first location found.

If the files contained versions, I could change that function to return the version as well.

And the do something in the test cases like:

```
    if Swedish dictionary version < 2.40:
          ... some tests ...
    else:
          ... some other tests ...

```

Getting the version number from the package names seems difficult,
package names are different on different distributions (It is actually
hunspell-en-US on Fedora, not hunspell-en-us).  Some distributions
package language variants into multiple packages, some into bigger
ones.

Another idea could be to calculate a md5sum or something similar of the dictionary file which was found and is loaded and use this as a kind of version.

```
    if md5sum of Swedish dictionary is in [...]:
          ... some tests ..
    elif md5sum of Swedish dictionary is in [... different list ...]:
          ... different tests ...
    else:
        skip tests
```

I would often need to add additional md5sums to the lists when
dictionaries are updated, even if the same tests still work because
the update was minor.

Would that make sense? Would it be worth the effort?

**Comment by gunnarhj** [comment] 2021-03-02 11:20
@mike-fabian: Thanks for the commit and for your detailed explanations!

> Another idea could be to calculate a md5sum or something similar of the dictionary file which was found and is loaded and use this as a kind of version.
>
>    if md5sum of Swedish dictionary is in [...]:
>          ... some tests ..
>    elif md5sum of Swedish dictionary is in [... different list ...]:
>          ... different tests ...
>    else:
>        skip tests
>
> I would often need to add additional md5sums to the lists when
> dictionaries are updated, even if the same tests still work because
> the update was minor.
>
> Would that make sense? Would it be worth the effort?

Well, personally I don't think it would be worth it. I take it that if those tests would fail on Fedora, you would investigate and fix it before releasing a new version, which means that also Debian/Ubuntu benefit from the safety the tests bring even if we don't run those particular tests ourselves.

It's fine with me to keep a distro patch which disables a couple of tests involving en_US and sv_SE dicts. If you agree that's a sensible way to handle it going forward, please feel free to close this issue again.

**Comment by mike-fabian** [comment] 2021-03-02 14:58
OK, thank you, then I'll close this for now.

**Closed by mike-fabian** 2021-03-02 14:58 UTC
