### ISSUE TITLE
Phrases inside parentheses are treated as a single word

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#223] opened 2021-08-20 13:05 UTC
Hi, Mike,

When one writes a phrase inside parentheses, ibus-typing-booster treats the entire phrase as a single word and not as being several words.

Thanks!

**Comment by mike-fabian** [comment] 2021-08-20 21:04
Example?

**Comment by psads-git** [comment] 2021-08-20 21:24
Please, Mike, see the example of line 1 in the attached video:

https://user-images.githubusercontent.com/75945439/130294711-eed3f8f8-bdfe-4e8a-84c7-61df44269066.mp4

**Comment by mike-fabian** [comment] 2021-08-22 16:18
This commit caused the behaviour reported here:

commit dfa8fa1f8137ae08ac107b183d0bd77fc6aeef0f
Author: Mike FABIAN <mfabian@redhat.com>
Date:   Fri Aug 6 10:18:24 2021 +0200

    Improve typing space or Tab when the cursor is not at the end of the preedit
    
    Resolves: https://github.com/mike-fabian/ibus-typing-booster/issues/198

**Comment by mike-fabian** [comment] 2021-08-22 16:20
The behaviour before this attempted fix wasn’t good either, when typing space while inside a preedit (**when no candidate was selected!**) committed and jumped to the end of the text.

I think the “best” behaviour is to commit and insert the space at the cursor position.

Trying to fix it that way ... ⏳

**Comment by psads-git** [comment] 2021-08-22 16:53
Thanks, Mike!

**Comment by mike-fabian** [comment] 2021-08-22 18:06
Here is a test build of 2.14.4:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/build/2532651/

I think this works better.

**Comment by psads-git** [comment] 2021-08-22 18:20
It seems to be now working perfectly, Mike. Thanks for your permanent readiness to improve ibus-typing-booster and hence its users benefits!

**Closed** 2021-08-22 19:04 UTC
Labels: bug

**Comment by mike-fabian** [comment] 2021-08-22 19:13
I released 2.14.4 now:

https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.14.4

it includes several other small fixes.

**Comment by mike-fabian** [comment] 2021-08-22 19:13
> It seems to be now working perfectly, Mike. Thanks for your permanent readiness to improve ibus-typing-booster and hence its users benefits!

Thank you very much for testing so carefully, your reports are really useful because they say exactly what the problem is.

**Comment by psads-git** [comment] 2021-08-28 12:30
A problem may be still remaining, Mike! When one writes

(word

all preedit suggestions begin with (. It is not clear whether ibus-typing-booster searches the database with 

(word

or with

word.

**Comment by psads-git** [comment] 2021-08-28 12:43
I am now certain that ibus-typing-booster searches the database with the word without parenthesis. Therefore, there is no issue.

**Comment by mike-fabian** [comment] 2021-08-30 09:32
> I am now certain that ibus-typing-booster searches the database with the word without parenthesis. Therefore, there is no issue.

Yes, it searches only for word.

https://github.com/mike-fabian/ibus-typing-booster/blob/main/engine/hunspell_table.py#L944

contains:

```
def _update_candidates(self) -> None:
        '''Update the list of candidates and fill the lookup table with the
        candidates
```

Which strips special characters from words:

```
               stripped_transliterated_string = (
                    itb_util.lstrip_token(self._transliterated_strings[ime]))
```

before doing the lookup:

```
                  candidates = self.database.select_words(
                            stripped_transliterated_string,
                            p_phrase=self._p_phrase,
                            pp_phrase=self._pp_phrase)
```

https://github.com/mike-fabian/ibus-typing-booster/blob/main/engine/itb_util.py#L130

contains the list of Unicode categories which are stripped:

```
CATEGORIES_TO_STRIP_FROM_TOKENS = (
    'Po', 'Pi', 'Pf', 'Ps', 'Pe', 'Pc', 'Pd'
)
```

( U+0028 LEFT PARENTHESIS has the Unicode category “Ps (Punctuation, Open)”

**Comment by psads-git** [comment] 2021-08-30 09:53
Thanks, Mike!
