### ISSUE TITLE
[BUG] Shortcut inserted when sending a Thunderbird message

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#476] opened 2024-01-04 19:08 UTC
Dear Mike,

I have a shortcut `ta` that, when pressing `control+enter` to send a message, the shortcut is inserted when sending the Thunderbird message where the shortcut was expanded.

Please, see the attached video.

Kind regards!

https://github.com/mike-fabian/ibus-typing-booster/assets/75945439/b4d7dac2-6aac-49a6-860b-de1551e8652d

**Comment by mike-fabian** [comment] 2024-01-04 22:24
I think I still don’t understand what you did there. 
I am not using Thunderbird, so I am trying to use it now for the first time to tr;y to reproduce this. 

`control+enter` is the keybinding in Thunderbird to send a message?

At the beginning of you video, you seem to type `ta` and this seems to expand to 

```
Thanks in advance,

Paul
```

I don't see how you select that expansion. I don't see the candidate list. Near the end of the video, `ta` appears below `Paul`.
What this what happend when you pressed `control+enter`?

**Comment by psads-git** [comment] 2024-01-04 22:29
> `control+enter` is the keybinding in Thunderbird to send a message?

Yes, Mike.

> At the beginning of you video, you seem to type `ta` and this seems to expand to
> 
> ```
> Thanks in advance,
> 
> Paul
> ```
> 
> I don't see how you select that expansion. I don't see the candidate list. Near the end of the video, `ta` appears below `Paul`. What this what happend when you pressed `control+enter`?

When I press `control+enter`, `ta` appears in the message.

**Comment by psads-git** [comment] 2024-01-04 22:30
I expand the shortcut by writing:

`ta + tab + enter`.

**Comment by mike-fabian** [comment] 2024-01-04 22:35
> I expand the shortcut by writing:
> 
> `ta + tab + enter`.

Ah, OK. The  candidate list is outside of the area of the video then, I guess?

**Comment by psads-git** [comment] 2024-01-04 22:45
Yes, Mike. Since `ta` is a shortcut, it is the first of the candidate list.

**Comment by mike-fabian** [comment] 2024-01-04 23:15
OK, as I have not used Thunderbird before and just started it for the first time now, it seems busy reading half a million mails from all my folders and is completely unresponsive while doing that. I think I'll let Thunderbird finish doing that and test then.

**Comment by psads-git** [comment] 2024-01-04 23:18
That is fine, Mike! But maybe it is not necessary to configure any account in thunderbird. Or, even better, configure a random fake account -- you do not need to send any e-mail to reproduce the bug.

**Comment by mike-fabian** [comment] 2024-01-05 23:07
I can reproduce the problem now. It seems to happen **only** for shortcuts which expand to multiple lines.

**Comment by psads-git** [comment] 2024-01-05 23:26
Great, Mike! 

This bug is new, as I use multi-line expansion shortcuts in Thunderbird almost daily and it had never occurred.

**Comment by mike-fabian** [comment] 2024-01-05 23:27
It has nothing to do especially with the `control+enter` or with sending a message. It happens always when edit area looses input focus. 

In this video, I type `\test` which is a shortcut expanding in multiple lines, then I type `control+enter` to send the message.
The problem is seen.

Then I delete everything again and repeat, I type `\test` and expand the shortcut but after that I just click with the mouse into the "Subject" line. The problem is seen as well. 

In both cases the message body entry area looses input focus, in the first case because the dialog pops up whether to send the message or not (and that dialog takes the input focus). In the second case because the subject area gets input focus. 

https://github.com/mike-fabian/ibus-typing-booster/assets/2330175/0200bc14-b690-4f82-8723-26075dbfc42a

**Comment by psads-git** [comment] 2024-01-05 23:41
The annoying thing is that if there is no pop-up window and the message gets sent, the shortcut goes included in the message, Mike.

**Comment by mike-fabian** [comment] 2024-01-06 00:10
This commit seems to fix it: https://github.com/mike-fabian/ibus-typing-booster/commit/725e3f006c965e892c734385002696dcbbde614e

I tried to just hide the preedit when it because empty instead of really clearing it to an empty string. I did that recently because of the disappearing character problems, doing many actions like commit, forward_key_event, update_preedit,... during the processing of a key event sometimes cause problems. I had hoped that hiding the preedit is a “gentler” action which might be less likely to trigger these extra calls to do_reset() which caused the disappearing characters. 

But hiding the preedit is not enough, I have to really clear it to an empty string. Because on focus out, a non-empty preedit is committed, even when it is hidden. 

But I also have improved `do_reset()` recently to not clear the input if the preedit is already empty when `do_reset()` is called. 

Therefore, even if this clearing of the preedit instead of hiding it causes an extra call to `do_reset()` that should be no problem now.

**Comment by mike-fabian** [comment] 2024-01-06 00:11
ibus-typing-booster-2.24.11 builds with the above fix are at https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

**Comment by psads-git** [comment] 2024-01-06 00:20
Thanks, Mike! It seems it fixes the issue!

**Closed** 2024-01-06 20:39 UTC
Labels: bug

**Comment by mike-fabian** [comment] 2024-01-06 20:41
https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.24.11
