### ISSUE TITLE
Add option to choose whether to start up in direct input mode (was: Icon on the system tray flickers)

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#169] opened 2021-07-23 11:45 UTC
When input mode is turned off, the icon on the system tray flickers when opening or closing a program, gedit for example. Please, see the attached video:

Thanks, Mike!

https://user-images.githubusercontent.com/75945439/126777275-a4ef555f-b1a8-4d4e-878d-ac86516d4d2e.mp4

**Comment by mike-fabian** [comment] 2021-07-25 18:46
So you see a 🐌 icon because input mode is off.

Then you open gedit and see the 🚀 icon for a short moment (which stands for input mode on, but you didn't turn input mode on, you just opened gedit). And after a short moment the 🚀 icon turns into the 🐌 icon again. 

Is that right?

**Comment by mike-fabian** [comment] 2021-07-25 18:48
OK, I can reproduce that with my i3 windowmanager desktop. The icon in the i3bar systemtray area flickers from snail to rocket and back.

**Comment by mike-fabian** [comment] 2021-07-25 18:51
Same behaviour with ibus-anthy (a Japanese input method) and ibus-table.

**Comment by mike-fabian** [comment] 2021-07-25 19:23
I am afraid this is an ibus problem and not an ibus-typing-booster problem.

**Comment by psads-git** [comment] 2021-07-25 19:36
Thanks, Mike. That is something not very serious.

I use a keyboard shortcut to toggle the input mode, as a way to turn on/off ibus-typing-booster by using the keyboard.

**Comment by mike-fabian** [comment] 2021-07-25 19:40
Here you can see the same in an Xfce desktop with the ibus-anthy input method.

First I use Super+Space to select ibus-anthy.

For a short moment, the icon is visisble in the panel, then replaced with the input mode indicator (Looks like "_A" in dark purple)

Then I open gedit and the icon is visible again for a short moment and again replaced with the input mode indicator.

Then I close gedit and it repeats, the icon is visible for a short moment and then replaced with the  input mode indicator.
 
https://user-images.githubusercontent.com/2330175/126911254-489313cd-6a4c-4ab0-91c7-c6d0a1921392.mp4

**Comment by psads-git** [comment] 2021-07-25 19:47
Thanks, Mike.

There is something that seems to be absent and that you may want to add: A way of setting up the state of the input mode with which ibus-typing-booster should start after a computer reboot.

**Comment by mike-fabian** [comment] 2021-07-25 19:53
The input mode indicator is actually text and the icon is a .png or .svg (or maybe .jpg?) picture.

In case of Anthy it is clearly visible that the icon is a picture. You cannot see that the input mode is text, but it actually is.

In case of ibus-typing-booster the icon is one of these:

$ rpm -ql ibus-typing-booster | grep png
/usr/share/icons/hicolor/128x128/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/16x16/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/22x22/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/256x256/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/32x32/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/48x48/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/64x64/apps/ibus-typing-booster.png
mfabian@taka:~
$ 

which I created using the google-noto-color-emoji font.

The input mode indicators 🚀 and 🐌  are actually text, but the text contains only emoji. How they look like depends on the emoji font used. If google-noto-color-emoji is used, the icon shown when ibus-typing-booster is selected looks identical to the emoji text based input mode indicator using the rocket emoji.

ibus has a setting to use different input methods in different windows, the default is to use the same input method for the whole desktop. But if you want you could use for example ibus-anthy for the terminal and ibus-typing-booster for gedit.

Then switching between the terminal and gedit would switch between  the input methods.

Even if the same input method is used for the whole desktop, it looks like opening gedit switches to ibus-typing-booster.
Closing gedit again switches to ibus-typing-booster because now the focus is on the terminal which also uses ibus-typing-booster.

If you use Super+Space to switch input methods you see the same.

Switching to an input method shows the icon first (if the input method has an icon) and then to the input mode (if the input methods has input modes **and** tries to display the input mode in the panel)

**Comment by mike-fabian** [comment] 2021-07-25 19:58
> Thanks, Mike.
> 
> There is something that seems to be absent and that you may want to add: A way of setting up the state of the input mode with which ibus-typing-booster should start after a computer reboot.

ibus-table (which I also maintain) has an option for this.
![ibus-table-input-mode](https://user-images.githubusercontent.com/2330175/126911811-01c8cf17-cd15-4832-830e-c937f66be961.png)

**Comment by mike-fabian** [comment] 2021-07-25 20:00
In ibus-table, the input mode toggle exists **always**. That makes it easy to add that option.

In ibus-typing-booster, the input mode exists **only** if the keybinding for the command `toggle_input_mode_on_off` is  not empty.

**Comment by mike-fabian** [comment] 2021-07-25 20:03
For example I could add an option, maybe as a checkbox like this:

[✓] Direct input on startup 

And if that option is checked, after a reboot, a restart of your desktop or a `ibus restart` on the command line, ibus-typing-booster would start in direct input mode (i.e. in the “switched off” mode).

**Comment by psads-git** [comment] 2021-07-25 20:06
That would be perfect, Mike!

I am going to install `ibus-table`.

**Comment by mike-fabian** [comment] 2021-07-25 20:06
The problem is that this option makes no sense when there is no keybinding set for `toggle_input_mode_on_off`.

I could make it so that this option only appears **if** there is a keybinding for `toggle_input_mode_on_off`.

And if you remove the keybinding for `toggle_input_mode_on_off`, the option “[✓] Direct input mode on startup” would be hidden again.

The value in gsettings/dconf would still be there but it would be ignored when not keybinding for `toggle_input_mode_on_off` is set, without that keybinding ibus-typing-booster would always be on on startup.

Would htat make sense?

**Comment by mike-fabian** [comment] 2021-07-25 20:09
Would it be confusing if that option is only shown when there is a keybinding for  `toggle_input_mode_on_off` and hidden **and** its value ignored when there is no such keybinding?

Or would that be understandable?

Showing the option **always** even when there is no such keybinding, doesn’t really seem to make sense...

**Comment by mike-fabian** [comment] 2021-07-25 20:10
Or, I could show that option **always** and **always** add the menu in the panel to switch the input mode between on and off even if there is no keybinding for this.

**Comment by psads-git** [comment] 2021-07-25 20:12
> Or, I could show that option **always** and **always** add the menu in the panel to switch the input mode between on and off even if there is no keybinding for this.

That seems fine to me, Mike!

**Comment by mike-fabian** [comment] 2021-07-25 20:14
> > Or, I could show that option **always** and **always** add the menu in the panel to switch the input mode between on and off even if there is no keybinding for this.
> 
> That seems fine to me, Mike!

That is what I do in ibus-table, the menu and the option to choose whether to use direct input on startup are **always** there, even if there is no keybinding to toggle this.

**Comment by psads-git** [comment] 2021-07-25 20:19
That is OK to me, but other users may not know about ibus-table, Mike!

**Comment by mike-fabian** [comment] 2021-07-25 20:30
ibus-table is something very different from ibus-typing-booster, ibus-table is mostly for some rare Chinese input methods like Cangjie and Wubi.

Most Chinese, Japanese, and Korean (“CJK”) input methods have input modes, so users of these input methods know about input modes and are not confused by something like “Direct input mode”.

ibus-typing-booster supports many languages but does **not** support Chinese and Japanese (it does support Korean but I have not feedback from Korean users so far so I cannot tell how good it is for Korean).

As input methods for languages other than CJK usually do **not** have a direct input mode (one can only switch away from the input method to a pure keyboard layout to switch it off), users of ibus-typing-booster who are not used to CJK input methods might be surprised about the existance of a direct input mode and wonder why it exists at all.

So I tried to hide from “normal” users by making it appear only if a keybinding is set for this.

A user who got that far to set a keybinding for this will know what he is doing.

I wonder whether that hiding is necessary. Would it be OK to give that up and show the option whether to start up in direct input mode **always** and also show the menu entry in the panel to switch between direct and real input mode **always**.
But still keep the keybinding empty by the default!

I can do that and I think that might be less confusing than hide the new option and the menu entry when there is no keybinding.

There is some risk to confuse users with offering a direct input mode, but making the new option only appear when there is a keybinding might also be confusing. But only confusing to some experts, normal users would never see that option if it is hidden when the keybinding is empty.

**Comment by psads-git** [comment] 2021-07-25 20:35
> I wonder whether that hiding is necessary. Would it be OK to give that up and show the option whether to start up in direct input mode **always** and also show the menu entry in the panel to switch between direct and real input mode **always**.
> But still keep the keybinding empty by the default!

That seems OK to me, Mike!

**Comment by psads-git** [comment] 2021-07-25 20:44
You may want to write something like the following near the option:

_Ignored if the respective keybinding is empty_.

**Comment by mike-fabian** [comment] 2021-07-26 06:11
I changed the title because we are talking mostly about adding that new option now and I cannot fix the flicker from the icon to the input mode indicator anyway (It must be something in ibus and it might even be intentional to show the icon first for a moment when switching to an input method and then the input mode indicator).

**Comment by mike-fabian** [comment] 2021-07-26 06:15
> You may want to write something like the following near the option:
> 
> _Ignored if the respective keybinding is empty_.

I could do that in the tooltip. But I think hiding that option if the keybinding is empty would be enough.

And if we show it always, then it does not need to be ignored when the keybinding is empty because one can change the input mode not only via the keybinding but also via the menu entry in the panel.

**Comment by psads-git** [comment] 2021-07-26 10:13
> I changed the title because we are talking mostly about adding that new option now and I cannot fix the flicker from the icon to the input mode indicator anyway (It must be something in ibus and it might even be intentional to show the icon first for a moment when switching to an input method and then the input mode indicator).

**Comment by psads-git** [comment] 2021-07-26 10:14
> > You may want to write something like the following near the option:
> > _Ignored if the respective keybinding is empty_.
> 
> I could do that in the tooltip. But I think hiding that option if the keybinding is empty would be enough.
> 
> And if we show it always, then it does not need to be ignored when the keybinding is empty because one can change the input mode not only via the keybinding but also via the menu entry in the panel.

**Comment by psads-git** [comment] 2021-07-26 10:15
> I could do that in the tooltip. But I think hiding that option if the keybinding is empty would be enough.

I agree, Mike.

**Comment by mike-fabian** [comment] 2021-07-26 11:24
I have another idea for the option which I like better:

[✓] Remember input mode  (on/off)

Tooltip: “If this option is checked, the input mode, i.e. whether ibus-typing-booster is switched on or off, is remembered even if the session is restarted”

That fits better to how the option:

[✓] Remember last used preedit input method

works.

OK?

**Comment by psads-git** [comment] 2021-07-26 11:27
> I have another idea for the option which I like better:
> 
> [✓] Remember input mode (on/off)
> 
> Tooltip: “If this option is checked, the input mode, i.e. whether ibus-typing-booster is switched on or off, is remembered even if the session is restarted”
> 
> That fits better to how the option:
> 
> [✓] Remember last used preedit input method
> 
> works.
> 
> OK?

Perfect, Mike!

**Comment by mike-fabian** [comment] 2021-07-26 17:25
Do you use Fedora? Could you test if I make a test package for Fedora?

**Comment by psads-git** [comment] 2021-07-26 17:33
Yes, Mike. I do use Fedora 34.

**Comment by mike-fabian** [comment] 2021-07-26 21:18
Here is a build for Fedora 34:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/build/2349945/

It contains these changes:

- Play an error sound when a compose sequence results in an empty string
- Don’t include the system compose files unconditionally if a user compose file exists
- Add option to choose whether to start up in direct input mode
- Change default input methods for Indian locales to inscript2

**Comment by psads-git** [comment] 2021-07-26 22:27
Thanks, Mike! I have just rebooted and the input mode was remembered. Moreover, the input mode is remembered after having restarted ibus-typing-booster.

**Comment by mike-fabian** [comment] 2021-07-27 06:07
Did you notice that the option is hidden when there is no keybinding?

I might reconsider this and show the option to remember the input  mode and the menu entry to switch ibus-typing-booster on/off always.

But for the moment I made this hidden unless a keybinding for `toggle_input_mode_on_off` exists, so it is an “advanced option only for experts”.

**Comment by psads-git** [comment] 2021-07-27 10:12
Thanks, Mike. Everything is working as you describe. And yes, the option is hidden when there is no keybinding.

**Comment by mike-fabian** [comment] 2021-07-27 12:39
New build here:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/build/2351011/

Should make no difference for remembering the input mode, I didn’t change anything there.
But there are some changes in the compose support to make it look and feel like the compose support in recent Gtk:

- Make Compose preedit less intrusive, show compose key only in the middle of the sequence or when it is the only key so far
- Use · U+00B7 MIDDLE DOT instead of ⎄ U+2384 COMPOSITION SYMBOL to display Multi_key in pre-edit.

**Comment by psads-git** [comment] 2021-07-27 14:35
Thanks, Mike! It seems to be working perfectly fine.

**Closed** 2021-07-27 16:01 UTC
Labels: enhancement

**Comment by mike-fabian** [comment] 2021-07-27 16:06
https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.12.0
