### ISSUE TITLE
Ctrl+A/selection overwriting behaves weird

### ISSUE THREAD

**Issue by rugk** [mike-fabian/ibus-typing-booster#35] opened 2018-05-21 16:03 UTC
![weirdctrla](https://user-images.githubusercontent.com/11966684/40317237-2f549b50-5d21-11e8-9deb-0958b709eab9.gif)

This even happened when I wanted to save the GIF:

![grafik](https://user-images.githubusercontent.com/11966684/40317213-23379642-5d21-11e8-92e6-46855d4dd672.png)

I have the "Qt bug workaround" active, but it happened before anyway, so I don't think it is related.

**Comment by mike-fabian** [comment] 2018-05-26 08:58
This seems to be the same for all ibus engines. So it is not a bug in ibus-typing-booster.

I tested with ibus-kkc and it behaves exactly the same  as ibus-typing-booster as far as
overwriting selections is concerned. 

It could also be a Gnome problem because it seems to work fine for me in firefox.

I close this because  I am pretty sure that this is not an ibus-typing-booster bug.

**Closed by mike-fabian** 2018-05-26 08:58 UTC

**Comment by rugk** [comment] 2018-05-26 09:19
Okay, reported at https://github.com/ibus/ibus/issues/2013
