### ISSUE TITLE
[BUG] Underscores are always stripped, whatever the emoji trigger character is.

### ISSUE THREAD

**Issue by vctls** [mike-fabian/ibus-typing-booster#432] opened 2023-02-28 09:32 UTC
**Describe the bug**
The underscore character always gets stripped, whatever I put in the "Emoji character trigger" setting, and whatever I type afterwards. I'm not sure the  is actually related to this setting, but I can't find anything else.

**To Reproduce**
I'm not sure. It always behaved like this since I installed it.

**Expected behavior**
The underscores should not be stripped.

**Screenshots or videos**
![Peek 2023-02-28 10-28](https://user-images.githubusercontent.com/18054077/221810842-68894c5e-16c8-40cc-91fd-a3c85f0ba459.gif)
![image](https://user-images.githubusercontent.com/18054077/221810945-c6392724-c4df-4749-aa68-cbf5c4143d27.png)

**ibus-typing-booster version?**
2.15.25

**ibus version?**
1.5.26

**Distribution and version?**
Ubuntu 22.04.2 LTS

**Desktop and version?**
Gnome 42.5

**Xorg or Wayland?**
Xorg

**Additional context**
I'm using the BÉPO French layout.

**Comment by mike-fabian** [comment] 2023-02-28 11:42
I cannot reproduce this with a "English US" keyboard layout, so I guess it must have something to do with the BÉPO French layout.

I will check ...

**Comment by mike-fabian** [comment] 2023-02-28 11:50
OK, this happens because with the BÉPO French layout you type an `_` by typing `AltGr+space`. 

And Typing Booster uses the key combination `AltGr+space` to insert a literal space into the preedit.

So all the underscores you are trying to type are converted into spaces and inserted into the preedit and when the preedit is finally committed, the underline indicating the preedit vanishes and only the spaces remain.

I am thinking about how to fix this ...

**Comment by mike-fabian** [comment] 2023-02-28 13:15
This attempt to fix the emoji lookup for the German neo2 layout didn’t really fix the emoji lookup as intended and caused the problem reported in this issue here (The German neo2 layout now suffers from exactly the same problem as reported here, space is inserted into the preedit instead of `_` as intended:

commit 0da5d094c89435553e3f77e8d4f6e8a3e56dbd59
Author: Mike FABIAN <mfabian@redhat.com>
Date:   Mon Sep 13 13:53:43 2021 +0200

    Add 'G-_' to 'G- ' as exceptions which must not trigger commits but insert into the preedit
    
    Resolves: https://github.com/mike-fabian/ibus-typing-booster/issues/243
    Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2002199
    
    The German neo2 layout uses ISO_Level3_Shift+v (= CapsLock+w on a QWERTY layout)
    to type an underscore '_'. That means when an underscore is typed using
    that layout, key.msymbol is 'G-_'. This triggered a commit instead of inserting
    the '_' into the preedit which made it impossible to add a '_' to the preedit
    to trigger the emoji mode.
    
    This commit fixes this problem by making another exception for 'G-_'.

**Comment by mike-fabian** [comment] 2023-02-28 13:17
See also: https://github.com/mike-fabian/ibus-typing-booster/issues/243

**Comment by mike-fabian** [comment] 2023-02-28 13:17
```diff
$ git diff 
diff --git a/engine/hunspell_table.py b/engine/hunspell_table.py
index 8fbdc833..c279e5fd 100644
--- a/engine/hunspell_table.py
+++ b/engine/hunspell_table.py
@@ -6590,7 +6590,7 @@ class TypingBoosterEngine(IBus.Engine): # type: ignore
                         self._current_case_mode = 'lower'
             if (key.msymbol in ('G- ', 'G-_')
                 and not self._has_transliteration([key.msymbol])):
-                insert_msymbol = ' '
+                insert_msymbol = key.unicode # ' ' for 'G- ' and '_' for 'G- '
             else:
                 insert_msymbol = key.msymbol
             if (not self._is_candidate_auto_selected
```
This should fix it correctly.

**Comment by vctls** [comment] 2023-02-28 13:32
Thank you! I wasn't sure if those two issues were connected.

**Comment by mike-fabian** [comment] 2023-02-28 13:46
I am preparing a new release with that fix and updated Swedish translations. So there  will be builds for Fedora soon.

But as you are on Ubuntu, it might take a bit longer until you get the update.

So if you like, you could try to edit `/usr/share/ibus-typing-booster/engine/hunspell_table.py` (as root), save it and restart ibus.
It is only a one line change, look for this line:

```
mfabian@fedora:~
$ grep "insert_msymbol = ' '" /usr/share/ibus-typing-booster/engine/hunspell_table.py
                insert_msymbol = ' '
mfabian@fedora:~
$ 
```

(There should be only one line containing `insert_msymbol = ' '`)

And change that line into

```
insert_msymbol = key.unicode # ' ' for 'G- ' and '_' for 'G-_'
```

as in the patch in my last comment.

Would be nice if you can test this while I am preparing the release.

**Closed** 2023-02-28 14:56 UTC
Labels: bug

**Comment by mike-fabian** [comment] 2023-02-28 14:59
https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.22.1

**Comment by mike-fabian** [comment] 2023-02-28 15:09
Video showing that typing `_` works with ibus-typing-booster-2.22.1 and the BÉPO French layout:

https://user-images.githubusercontent.com/2330175/221894575-ede73fc9-500f-40d0-b7cd-e1e06a076d15.mp4

**Comment by vctls** [comment] 2023-03-01 08:18
Yep, can confirm it's working! Thank you very much!
