### ISSUE TITLE
Does not recognize KeePassXC's password input as password

### ISSUE THREAD

**Issue by rugk** [mike-fabian/ibus-typing-booster#37] opened 2018-05-22 09:54 UTC
…it shows my password… :cry: 

I thought only terminals are affected. KeePassXc seems to use Qt (5.10.1).

**Comment by mike-fabian** [comment] 2018-05-22 10:29
I am using keepassx-2.0.3-6.fc28.x86_64 which does  not do that. It seems to be a Qt4  application.

**Comment by mike-fabian** [comment] 2018-05-22 10:38
I should probably try the keepassxc now. Is that compatible, i.e. will it read and write my existing database?

**Comment by rugk** [comment] 2018-05-22 10:58
Yes, it is compatible of course. It even supports the newer formats of KeePass.

**Comment by mike-fabian** [comment] 2018-05-27 17:51
OK， I tried keepassxc. 
The problem that the preedit is visible on the password field seems to occur with *all* ibus engines.
I tried ibus-typing-booster, ibus-kkc, ibus-anthy, ibus-libpinyin, ibus-m17n.
When using keepassx, *none* of these engines shows the password, bullets are shown when using any of  these  engines.

So I think this is a problem in KeePassXc not giving the information that this is a password field to the input engines.

**Comment by mike-fabian** [comment] 2018-05-27 18:07
Looking at the debug output in ~/.local/share/ibus-typing-booster/debug.log
(debugging turned on by editing /usr/libexec/ibus-engine-typing-booster and setting
export IBUS_TYPING_BOOSTER_DEBUG_LEVEL=2), I see that no keyevents  at all reach ibus-typing-booster when typing into the password field of keepassx. But all keyevents get through to ibus-typing-booster when typing into the "keyfile" field of keepassx.

When doing the same with keepassxc, all keyevents get through to ibus-typing-booster both when typing into the "password" field and when typing into the "keyfile" field. So keepassx somehow manages to switch off input methods when typing into the password field whereas keepassxc does not do that. 

The behaviour is the same for all ibus input methods I tested.

**Comment by mike-fabian** [comment] 2018-05-27 18:08
So I think there seems to be something wrong with keepassxc.

**Comment by rugk** [comment] 2018-05-27 21:06
Okay, reported at https://github.com/keepassxreboot/keepassxc/issues/2004.

**Comment by droidmonkey** [comment] 2018-05-28 02:51
We have not changed anything in the code regarding the password input field. This is likely a Qt5 issue...

**Comment by mike-fabian** [comment] 2018-05-28 05:52
Yes, it could be a Qt5 issue.

**Comment by mike-fabian** [comment] 2018-05-28 07:48
As a workaround, you can use

    env QT_IM_MODULE=somenonsene keepassxc

As Qt5 supports only the ibus input module, i.e. only QT_IM_MODULE=ibus actually works.
If you use anything else except "ibus", this disables input engines completely. 

So with this workaround, you don’t have ibus input in keepassxc *at* *all*, not only in the password field.
If you do not need ibus input in keepassxc, this workaround could help you.

**Comment by mike-fabian** [comment] 2021-08-07 11:54
On Fedora 34, with these versions of keepassxc and qt5:

keepassxc-2.6.6-1.fc34.x86_64
qt5-qtbase-gui-5.15.2-15.fc34.x86_64

it works correctly, input methods are correctly disabled in the password entry field.

**Comment by mike-fabian** [comment] 2021-08-07 11:54
I think I can close this now as it seems to work with a recent version  of Qt5.

**Closed by mike-fabian** 2021-08-07 11:54 UTC
Labels: bug in other software

**Comment by lkblkb** [comment] 2022-07-01 03:02
Sorry to necro post (I can open a new issue if needed). According to my experience there might be a reversion here. Booster is saving passwords from KeepassXC in db, which is pretty disconcerting. 

Using
> booster 2.15.25-1
> Keepassxc 2.50-2
> qt 6.3.0-3 (qtbase package)
> Manjaro (Arch) with KDE

**Comment by mike-fabian** [comment] 2022-07-01 07:57
Is the input enabled for you while typing into the password field?

I cannot reproduce this on Fedora  36 with:

keepassxc-2.7.1-3.fc36.x86_64
qt5-qtbase-gui-5.15.3-3.fc36.x86_64
ibus-typing-booster-2.16.3-1.fc36.noarch

(keepassxc seems to be a Qt5, not a Qt6 application on Fedora 36)

**Comment by lkblkb** [comment] 2022-07-04 02:15
> Is the input enabled for you while typing into the password field?

I assume you mean is typing-booster (TB) the current input and also "ON"? Yes to both. 

If this is the expected behavior (TB captures everything including passwords) then I guess I will keep doing my best to switch back to EN before using Keepass.

**Comment by droidmonkey** [comment] 2022-07-04 03:09
This is not our application.... KeePass original has version 2.50, not us. 

> Keepassxc 2.50-2

**Comment by mike-fabian** [comment] 2022-07-04 09:58
> > Is the input enabled for you while typing into the password field?
> 
> I assume you mean is typing-booster (TB) the current input and also "ON"? Yes to both.
> 
> If this is the expected behavior (TB captures everything including passwords) then I guess I will keep doing my best to switch back to EN before using Keepass.

No, you should not be able to type with typing-booster (TB) into the password field!

The version of keypassxc I have (keepassxc-2.7.1-3.fc36.x86_64) apparently disables ibus input in the password field. TB is automatically off if I type into the password field of keepassxc on Fedora 36. But after unlocking, I *can* type with TB into the search field in keepassxc.

So I think this is a problem with the version of keepassxc you are using. It doesn’t disable ibus input on the password field. And it does not give a hint that this is a password field either.

TB has this code at the beginning of processing a key event:

https://github.com/mike-fabian/ibus-typing-booster/blob/main/engine/hunspell_table.py#L5628

```
        if (not self._input_mode
            or (self._input_purpose
                in [itb_util.InputPurpose.PASSWORD.value,
                    itb_util.InputPurpose.PIN.value])):
            return self._return_false(keyval, keycode, state)
```

I.e. if the program typed into (here keepassxc) sets the `InputPurpose.PASSWORD` or `InputPurpose.PIN` hint, then it immediately returns and just passes the keys through without doing anything, i.e. TB disables itself in that case.

For the version of keepassxc I am using, this isn't even necessary because TB doesn’t even get any key events when the focus is on the password entry because keepassxc already disables this completely.

So I think this is a bug in the version of keepasxc you are using.

**Comment by mike-fabian** [comment] 2022-07-04 10:02
> This is not our application.... KeePass original has version 2.50, not us.
> 
> > Keepassxc 2.50-2

These versions confuse me. What is that keepassxc thing in Fedora 36 (keepassxc-2.7.1-3.fc36.x86_64)?

You say this is not your application. Are there several forks of keepassxc around?

**Comment by droidmonkey** [comment] 2022-07-04 10:32
Sorry @mike-fabian my comment was not directed to you. You are using the 'official's version of keepassxc from Fedora. 

@lkblkb is not using KeePassXC based on his version number he provided.

**Comment by mike-fabian** [comment] 2022-07-04 10:47
> Sorry @mike-fabian my comment was not directed to you. You are using the 'official' version of keepassxc from Fedora.
> 
> @lkblkb is not using KeePassXC based on his version number he provided. He is conflating the name keepassxc onto KeePass originals version.

Ah, OK, thank you! Then probably @lkblkb can solve the problem by upgrading to the official version of KeePassXC.

**Comment by lkblkb** [comment] 2022-07-05 02:20
@droidmonkey sir you are correct, although only about the fact that I can't read (I really am using KeepassXC!)
![image](https://user-images.githubusercontent.com/25714571/177236709-6751b038-bb2d-4d73-a14c-b1a4d2b91dff.png)
So I am in fact using KeepassXC 2.7.1-1

**Comment by droidmonkey** [comment] 2022-07-05 02:31
At this time there is not much we can do about the booster issue. We are using standard Qt LineEdit with masking mode for password fields. So this is either a Qt bug or a Booster bug.

**Comment by lkblkb** [comment] 2022-07-05 02:36
@droidmonkey I am also using ibus with RIME (Chinese input) and passwords are also captured. Not sure what this might imply.

**Comment by lkblkb** [comment] 2022-07-05 02:49
Update： moved from Firefox to Chromium for testing, seems to be a Firefox issue 🙄 I'd already started migrating back to Chromium, seems time to complete the move.

**Comment by lkblkb** [comment] 2022-07-05 04:04
Well sh*t I'm logging in to some other websites on Chromium (102.0.5005.65-1) and it seems many do not play nice and ibus remains active.

**Comment by lkblkb** [comment] 2022-07-07 02:07
Hope my last message does not seem rude. Just annoyed with Chrome.

**Comment by mike-fabian** [comment] 2022-07-07 09:34
Websites? Firefox? Chrome? 

That has nothing to do with KeePassXC.

Input methods are deactivated correctly for me on the password entry field of KeePassXC (keepassxc-2.7.1-3.fc36.x86_64).

If there are  problems with password input fields in Firefox and/or Chrome, then this is something different and you should open a new issue.

**Comment by lkblkb** [comment] 2022-07-08 09:31
@mike-fabian ahhhh yes, my mistake!
