### ISSUE TITLE
[BUG] Spurious words before suggestions 

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#529] opened 2024-08-26 11:34 UTC
I have just recorded the occurrence of the bug I mentioned yesterday, Mike: please, watch the attached video.

The steps I went through:

- Wrote the sentence.
- With the mouse placed the cursor in some space in the middle of the sentence.
- The last sentence word is placed before the `ibus-typing-booster`'s word suggestion.

I suspect that to reproduce the bug, one needs to type a word that starts with the same letter of the end of the sentence word.

https://github.com/user-attachments/assets/65022df2-344b-4a6e-95ff-d60615c89736

**Comment by psads-git** [comment] 2024-08-29 17:14
I am not very sure, but I guess not, Mike. Maybe I have noticed that on WhatsApp, because I use that a lot, contrarily to other applications.

I use WhatsApp on Firefox.

**Comment by psads-git** [comment] 2024-10-23 13:44
Thanks, Mike! That is good news that you can now reproduce it.

**Comment by mike-fabian** [comment] 2024-10-23 16:14
It does not  happen when WhatsApp is used in google-chrome.

**Comment by psads-git** [comment] 2024-10-23 16:19
Yes, Mike, I confirm that.

**Comment by mike-fabian** [comment] 2024-10-23 16:38
The reason why it does not happen in google-chrome is that google-chrome does not appear to support surrounding text. 

Firefox supports surrounding text and the problem occurs in the `do_reset()` function only when  surrounding text is supported. 

This patch makes the problem go away:

```patch
diff --git a/engine/hunspell_table.py b/engine/hunspell_table.py
index 2d9265ab..6519abb9 100644
--- a/engine/hunspell_table.py
+++ b/engine/hunspell_table.py
@@ -2601,6 +2601,7 @@ class TypingBoosterEngine(IBus.Engine): # type: ignore
         if DEBUG_LEVEL < 1:
             return
         if not self.client_capabilities & itb_util.Capabilite.SURROUNDING_TEXT:
+            LOGGER.debug('Surrounding text not supported.')
             return
         surrounding_text = self.get_surrounding_text()
         if not surrounding_text:
@@ -7725,7 +7726,8 @@ class TypingBoosterEngine(IBus.Engine): # type: ignore
                 LOGGER.debug('Surrounding text object is None. '
                              'Should never happen.')
                 return
-            if not text.endswith(self._current_preedit_text):
+            if not (text.endswith(self._current_preedit_text)
+                    or text.endswith(self._current_preedit_text + '\u200b')):
                 LOGGER.debug(
                     'Whatever caused the reset did not commit the preedit. '

```

This is not supposed to be the fix yet, this might have side effects, I need to investigate more.

I just noticed that WhatsApp seems to add a `U+200B ZERO WIDTH SPACE` at the end of the text one has just typed. I didn’t enter that zero width space, WhatsApp seems to do this. And because that extra zero width space is there, the test `if not text.endswith(self._current_preedit_text)` fails and the preedit is not cleared and then reappears a the new cursor position.

I will investigate more tomorrow, I just wanted to document here what I found so far ...

**Comment by mike-fabian** [comment] 2024-10-23 16:41
```
2024-10-23 18:39:11,414 hunspell_table.py line 2611 _update_candidates_and_lookup_table_and_aux DEBUG: surrounding_text = ['a \u200b', 2, 2]
```
In the `debug.log` when I have just typed `a b` and the `b` is still in preedit and the cursor still behind the b. There is this extra `\u200b` found in the surrounding text which I have not typed.

**Comment by mike-fabian** [comment] 2024-10-28 20:01
I have a workaround for reopening preedits when gtk3-im is used:
Sometimes, when a preedit was just reopened, a do_reset() call
happened (which should not have happened!).  If the do_reset() then
clears the input, one will loose the just reopened preedit.

To avoid this, I checked whether the complete surrounding test ended
with the current preedit still stored in
self._current_preedit_text. If this is the case, the input can be
cleared because it has apparently been correctly committed. It was not
a reopening of a preedit, it was juse moving the cursor to a different
position with the mouse which will trigger a commit of the preedit.
If the surrounding text did *not* end with the contents of the current
preedit, apparently a preedit had been reopened and the input should
not be cleared.

This worked only correctly, if the current preedit happened to be at
the end of the line. It was always broken when the current preedit was
**not** at the end of the line.

WhatsApp always seems to add a U+200B ZERO WIDTH SPACE after the
current cursor position. Therefore, when using WhatsApp in firefox,
the preedit was never really at the end of the line. When a preedit
which appeared to be at the end of the line was committed by clicking
with the mouse somewhere else in the line, the line actually ended
with the committed preedit followed by a U+200B ZERO WIDTH SPACE.

But the same problem can also be reproduced elsewhere in firefox and
also in gedit if the preedit is not at the end of the line.

I think the solution is to compare the contents of
self._current_preedit_text only with the surrounding text up to the
cursor positon.

Also, apply this workaround only when the im client uses gtk3-im, for
Wayland surrounding text works differently and has different contents
in this situation. The original problem the workaround is solving
occured on Gtk3, for other im clients that workaround is probably
useless anyway.

**Comment by mike-fabian** [comment] 2024-10-28 20:07
Video showing  how I can reproduce the problem with gedit on a i3 desktop (Xorg) On Fedora 40 with ibus-typing-booster-2.26.0:

https://github.com/user-attachments/assets/8ee1c13b-cf99-4f6e-b4e5-1ea94d63d77f

**Comment by mike-fabian** [comment] 2024-10-28 20:10
There are ibus-typing-booster-2.26.6 test builds in 
https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/
which should fix the issue.

**Comment by psads-git** [comment] 2024-10-28 20:10
Thanks, Mike! I suspected that the same issue also occurs in gedit, which now you confirm.

**Comment by psads-git** [comment] 2024-10-28 20:13
> There are ibus-typing-booster-2.26.6 test builds in https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/ which should fix the issue.

I will be testing that and then I will report you about how the new version is doing, Mike.

**Comment by psads-git** [comment] 2024-10-29 11:46
The new release, by some user action that I have not been capable of isolating, starts to precede words in the current word -- and it precedes the current  word with words that have been typed. 

Hoping to restore normal functionality, I restarted `ibus-typing-booster`, which led to a crash, with `ibus` being made unreachable (e.g., with `ibus resart`).

I will try to isolate the course of action that leads to the reported issue, Mike.

**Comment by mike-fabian** [comment] 2024-10-29 12:35
On Wayland or Xorg? Is that ibus-typing-booster-2.26.6 or an older version?

**Comment by psads-git** [comment] 2024-10-29 12:47
Thanks, Mike:

- `xorg`
- `ibus-typing-booster-2.26.6-1.fc40.noarch`

**Comment by mike-fabian** [comment] 2024-10-29 12:55
Hm, that works fine for me.

**Comment by psads-git** [comment] 2024-10-29 13:00
In general, Mike, it works fine, but there is a course of user action that leads to the reported issue. I believe I will isolate the reproducibility conditions.

**Comment by mike-fabian** [comment] 2024-10-29 14:21
> In general, Mike, it works fine, but there is a course of user action that leads to the reported issue. I believe I will isolate the reproducibility conditions.

OK, is is a relief to hear that it mostly works.

The patch to fix the issue here is rather small:
https://github.com/mike-fabian/ibus-typing-booster/commit/2483f11a92a83e05bcf55751d9e997edeec182cc

It limits avoiding to clear the input in a `do_reset()` to `gtk3-im` and if it is `gtk3-im` it avoids clearing the input only if the surrounding text up to the cursor ends with the current preedit text.

I.e. the input is cleared more often. 

But what you describe almost sounds like the original issue reported here,  doesn’t it?:

 > starts to precede words in the current word -- and it precedes the current word with words that have been typed.

That sounds like something is inserted again, just as if the input had not been cleared.

I am pretty sure the patch I made cannot cause this, so probably it is unrelated and has existed before, is that possible?

Apart from the very small patch to fix this issue here, the difference between 2.26.0 and 2.26.6 are only relevant to emoji-picker to fix the fallback problem reported in https://github.com/mike-fabian/ibus-typing-booster/issues/508 .
That cannot influence typing.

**Comment by mike-fabian** [comment] 2024-10-29 14:31
> Hoping to restore normal functionality, I restarted `ibus-typing-booster`, which led to a crash, with `ibus` being made unreachable (e.g., with `ibus resart`).

`ibus restart` unfortunately often causes some breakage. After `ibus restart` all XIM clients hang and have to be killed and restarted (for example `xterm` or `emacs`)

Luckily there are not so many XIM clients anymore, and for `emacs` I use

`(setq-default x-gtk-use-native-input t)`

which makes `emacs` avoid XIM and use `gtk3-im` instead, which works much better.

But on addition to the problems with XIM clients when using `ibus restart`, there are often other problems. I also sometimes saw crashes, sometimes ibus doesn't really restart but ends and I have to start it again with `ibus-daemon -dxr`.

As I need to restart very often during development of ibus-typing-booster, I restart only typing booster instead and not the whole ibus system. I do it with this small shell script which I did put in my `~/bin` directory:

```sh
#!/bin/bash

pgrep -u ${USER} -a -f /usr/share/ibus-typing-booster/engine/main.py
pkill -u ${USER} -f /usr/share/ibus-typing-booster/engine/main.py
sleep 1
pgrep -u ${USER} -a -f /usr/share/ibus-typing-booster/engine/main.py
echo "Now switch to some other engine and back to typing booster."
```

This kills only the current typing booster process. And as the script says in the last line, after killing typing booster one has to switch to some other input method and switch back to typing booster. Then a new typing booster process is started.

This works much better for me than restarting ibus, I can do that as often as I want without getting problems with XIM or ibus crashing.

**Comment by psads-git** [comment] 2024-10-29 16:41
I will be paying attention to isolate the way of reproducing the issue, and then I will report it here. Thanks, Mike!

**Comment by mike-fabian** [comment] 2024-10-29 17:08
> I will be paying attention to isolate the way of reproducing the issue, and then I will report it here. Thanks, Mike! 

If it doesn't introduce any regression, I could release 2.26.6 officially for Fedora.

If you report a new issue, I will fix that as well as soon as possible and make a 2.26.7.

I like to make a new release as soon as I have any improvement, even when it is only a small.
Because I don't when I will have the next improvement ready. It might take only a few days but if it takes weeks or months it would be a pity not to have released the available improvements earlier.

**Comment by psads-git** [comment] 2024-10-29 17:12
I agree, Mike. Please, go ahead with releasing 2.26.6 officially for Fedora!

**Closed as completed** 2024-10-29 18:24 UTC
Labels: bug

**Comment by mike-fabian** [comment] 2024-10-29 18:28
Fix included in https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.26.6
