### ISSUE TITLE
Toggling input mode through shortcuts is not working on some applications 

### ISSUE THREAD

**Issue by elhananjair** [mike-fabian/ibus-typing-booster#277] opened 2022-02-26 16:16 UTC
Hello there I have set a shortcut to toggle input mode, and while it works fine on some apps I am having problem on specifically chromium web browser. I couldn't toggle input modes with the shortcuts I have set, even if I switched the language outside chromium window, it only writes in English instead of a language I have switched too. 

**I am using ibus-typing-booster on Fedora 35 with KDE (wayland) 5.24.2**

**Comment by mike-fabian** [comment] 2022-02-27 10:50
Which shortcut did you set? Can you add a screenshot or video please?

ibus-typing-booster  gets the key events only if the focus is on a window/area where input with ibus is possible. So if you hit a key while the focus is for example on the desktop background where no input is possible, ibus-typing-booster cannot see that key and cannot do anything. But this is not what causes your problem, or is it?

**Comment by mike-fabian** [comment] 2022-02-27 11:30
Is the `imsettings-systemd` package installed?

Are the environment variables for ibus set?:

```
$ env | grep ibus 
GTK_IM_MODULE=ibus
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
```

**Comment by mike-fabian** [comment] 2022-02-27 12:09
I tried reproduce the problem (testing on Fedora 36, should make no difference to the Fedora 35 you are using in this case).
Package:

```
chromium-96.0.4664.110-7.fc36.x86_64
```

Then I tried with 4 desktops whether I can type with ibus-typing-booster or ibus-anthy into the url entry field of chromium-browser:

- Gnome (wayland):   does **not** work
- Gnome (Xorg): works
- Plasma(wayland): does **not** work
- Plasma(Xorg): works

So this looks to me as if input using ibus into chromium-browser works only on Xorg but not on Wayland.

Is that the same problem you are seeing or is your bug report about something different?

**Comment by mike-fabian** [comment] 2022-02-27 12:32
I have opened this bug for the problem that input with ibus into the chromium-browser does not work in Wayland:

https://bugzilla.redhat.com/show_bug.cgi?id=2058976

**Comment by elhananjair** [comment] 2022-02-27 17:49
> Which shortcut did you set? Can you add a screenshot or video please?
> 
> ibus-typing-booster gets the key events only if the focus is on a window/area where input with ibus is possible. So if you hit a key while the focus is for example on the desktop background where no input is possible, ibus-typing-booster cannot see that key and cannot do anything. But this is not what causes your problem, or is it?

Now I got it now, that's is one of my question. Since it didn't worked for me on chromium I thought that was a global issue.

**Comment by elhananjair** [comment] 2022-02-27 17:49
> Is the `imsettings-systemd` package installed?
> 
> Are the environment variables for ibus set?:
> 
> ```
> $ env | grep ibus 
> GTK_IM_MODULE=ibus
> XMODIFIERS=@im=ibus
> QT_IM_MODULE=ibus
> ```

Yeah I have installed and set those env. variables.

**Comment by elhananjair** [comment] 2022-02-27 17:51
> I tried reproduce the problem (testing on Fedora 36, should make no difference to the Fedora 35 you are using in this case). Package:
> 
> ```
> chromium-96.0.4664.110-7.fc36.x86_64
> ```
> 
> Then I tried with 4 desktops whether I can type with ibus-typing-booster or ibus-anthy into the url entry field of chromium-browser:
> 
> * Gnome (wayland):   does **not** work
> * Gnome (Xorg): works
> * Plasma(wayland): does **not** work
> * Plasma(Xorg): works
> 
> So this looks to me as if input using ibus into chromium-browser works only on Xorg but not on Wayland.
> 
> Is that the same problem you are seeing or is your bug report about something different?

that's is the exact problem am facing thank you @mike-fabian

**Comment by mike-fabian** [comment] 2022-02-27 19:18
> > I tried reproduce the problem (testing on Fedora 36, should make no difference to the Fedora 35 you are using in this case). Package:
> > ```
> > chromium-96.0.4664.110-7.fc36.x86_64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then I tried with 4 desktops whether I can type with ibus-typing-booster or ibus-anthy into the url entry field of chromium-browser:
> > 
> > * Gnome (wayland):   does **not** work
> > * Gnome (Xorg): works
> > * Plasma(wayland): does **not** work
> > * Plasma(Xorg): works
> > 
> > So this looks to me as if input using ibus into chromium-browser works only on Xorg but not on Wayland.
> > Is that the same problem you are seeing or is your bug report about something different?
> 
> that's is the exact problem am facing thank you @mike-fabian

Thank you for confirming!

Then I close this issue here because I cannot to anything to fix that in ibus-typing-booster, it seems to be a Wayland and/or Chromium problem.

**Closed by mike-fabian** 2022-02-27 19:18 UTC
Labels: bug in other software
