### ISSUE TITLE
Using enter for selecting suggestion?

### ISSUE THREAD

**Issue by rugk** [mike-fabian/ibus-typing-booster#32] opened 2018-05-21 15:49 UTC
https://github.com/mike-fabian/ibus-typing-booster/issues/31#issuecomment-390692864

**Comment by mike-fabian** [comment] 2018-05-22 08:33
Can you describe in more detail what the problem is here?

**Comment by rugk** [comment] 2018-05-22 09:51
STR:
1. In Firefox go to an input field (even the search box is possible)
2. Enter something.
3. Choose a suggestion by pressing "Down" key and "Enter".

What happens: Enter is actually also passed to Firefox, whcih adds a new line or – in case of search – starts the search.

What should happen: Just select suggestion and let me finish writing.

 I just saw this is maybe me not getting how one should select a suggestion (and 1-9 F1-9 are not a thing I'd like to use) The thing is it correctly highlights the elements with down and up keys, so I thought enter would be the way to go…

Because I can also reproduce it in gedit:
![enter](https://user-images.githubusercontent.com/11966684/40355269-43d1060a-5db6-11e8-87dc-74b787d9406e.gif)

**Comment by mike-fabian** [comment] 2018-05-22 10:17
That is actually on purpose. 
Because it saves having to type Enter again if you want an Enter after the commit.

Whatever key you use to commit is added after the commit.

I.e. if you commit with Space, a space is added, if you commit with Enter, a Enter is added, 
if you commit with arrow-right, an arrow-right is added (cursor movement),
if you commit with arrow-left, an arrow-left is added.

If you really don’t want to add anything, you can commit using the number keys (1, 2, 3, ...) (only if 
the option to disable committing with number keys is not used).
Oŗ one can always commit with the F-keys (F1, F2, F3, ...) without
adding anything after the commit. One can also commit by clicking the candidate with the mouse
without adding any keys.

**Comment by mike-fabian** [comment] 2018-05-22 10:17
I close this because  this is on purpose.

**Closed by mike-fabian** 2018-05-22 10:17 UTC

**Comment by rugk** [comment] 2018-05-22 10:19
Ah, so I should just continue to type. That's clever, but was not obvious to me… :laughing:
