### ISSUE TITLE
Duplicating text on LibreOffice Writer

### ISSUE THREAD

**Issue by iliekprogrammar** [mike-fabian/ibus-typing-booster#87] opened 2020-02-26 17:11 UTC
![ibus-typing-booster bug-2020-02-27_00 20 57](https://user-images.githubusercontent.com/51074650/75367884-ee85c080-58fb-11ea-9c78-94910faa7f49.gif)
In this gif, i typed some words. Afterwards, i pressed backspace one by one until all of the words are deleted. Next, i did the same test using <kbd>CTRL</kbd>+<kbd>backspace</kbd> and it works fine.

![ibus-typing-booster bug-2020-02-27_00 24 04](https://user-images.githubusercontent.com/51074650/75367893-f34a7480-58fb-11ea-82fe-9f35a988b4f1.gif)
In this gif, i typed some words. After typing `word-c` i moved my cursor, meaning that i _didn't commit_ on that word. Next, i typed <kbd>space</kbd> and `word-c` suddenly appears. The same test was done on `word-d`. Sure, i should have committed those words but the duplication effect shouldn't happen regardless.

**Comment by mike-fabian** [comment] 2020-02-27 13:59
This is on Wayland, I guess?

**Comment by mike-fabian** [comment] 2020-02-27 15:28
The problem in your first gif is also reported here: 

https://bugzilla.redhat.com/show_bug.cgi?id=1637647

This is caused by broken support for surrounding text, especially when using Wayland, but also in some other cases.

I will “fix” this by making the option “Arrow keys can reopen preedit” (you can find that in the setup tool) also switch off the reopening of the preedit for Backspace. This option is off by default,
and in the next release it will disable the reopening of the preedit not only when using the arrow keys but also when using backspace.

**Comment by mike-fabian** [comment] 2020-02-27 15:36
The problem in your second gif is something else. I cannot even reproduce it at the moment, I don’t get the duplication. 

Most likely you will get that duplication with *all* ibus input methods, not only with ibus-typing-booster. Can you try that please? I.e. use some other ibus input method and see whether you get the duplication as well? If yes, it iwould be not be a ibus-typing-booster bug.

**Comment by mike-fabian** [comment] 2020-02-27 21:05
A fix/workaround for your first problem is  included in

https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.8.1

Check the option “Arrow keys can reopen a preedit” in the setup tool, it should be off, then you should not have this problem anymore (It is off by default).

This is the commit fixing your first problem:

https://github.com/mike-fabian/ibus-typing-booster/commit/956b0cf51f7d3803bb605695c4ccc6fea77524a8

**Comment by mike-fabian** [comment] 2020-02-27 21:07
I am closing this issue now.

For your second problem, please check whether it happens with other ibus input method as well. If yes, it is not an ibus-typing-booster problem. If it happens only with ibus-typing-booster, please open a new issue.

**Closed by mike-fabian** 2020-02-27 21:07 UTC

**Comment by iliekprogrammar** [comment] 2020-03-07 11:02
Sorry for the late reply, I was busy with IRL stuff.

Anyway, I encountered both bugs using X11. The first gif was fixed, thank you very much.

Additionally, The second gif was reproducible with ibus-anthy too, so I guess it wasn't ibus-typing-booster problem.
